#pragma config(Sensor, in3,    inLightSensor,  sensorReflection)
#pragma config(Sensor, in4,    outLightSensor, sensorReflection)
#pragma config(Sensor, dgtl4,  armSwitch,      sensorTouch)
#pragma config(Sensor, dgtl5,  allClearSwitch, sensorTouch)
#pragma config(Motor,  port3,           windowFlashlight1, tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port4,           doorFlashlight, tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port5,           windowFlashlight2, tmotorVexFlashlight, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void LEDShow()
{
	turnLEDOn(red1);
	wait(0.5);
	turnLEDOn(blue1);
	wait(0.5);
	turnLEDOn(red2);
	wait(0.5);
	turnLEDOn(blue2);
	wait(0.5);
	turnLEDOff(red1);
	turnLEDOff(blue1);
	turnLEDOff(blue2);
	turnLEDOff(red2);
	wait(0.2);
	turnLEDOn(red1);
	turnLEDOn(red2);
	wait(0.1);
	turnLEDOn(blue1);
	turnLEDOn(blue2);
	turnLEDOff(red1);
	turnLEDOff(red2);
	wait(0.1);
	turnLEDOff(blue1);
	turnLEDOff(blue2);
	turnLEDOn(red1);
	turnLEDOn(red2);
	wait(0.1);
	turnLEDOn(blue1);
	turnLEDOn(blue2);
	turnLEDOff(red1);
	turnLEDOff(red2);
	wait(0.1);
	turnLEDOff(blue1);
	turnLEDOff(blue2);
	turnLEDOn(red1);
	turnLEDOn(red2);
	wait(0.1);
	turnLEDOn(blue1);
	turnLEDOn(blue2);
	turnLEDOff(red1);
	turnLEDOff(red2);
	wait(0.1);
	turnLEDOff(blue1);
	turnLEDOff(blue2);
	turnLEDOn(red1);
	turnLEDOn(red2);
	wait(0.1);
	turnLEDOn(blue1);
	turnLEDOn(blue2);
	turnLEDOff(red1);
	turnLEDOff(red2);
	wait(0.1);
	turnLEDOff(blue1);
	turnLEDOff(blue2);
	wait(0.2);
	turnLEDOn(blue1);
	turnLEDOn(red2);
	wait(0.2);
	turnLEDOn(red1);
	turnLEDOn(blue2);
	turnLEDOff(blue1);
	turnLEDOff(red2);
	wait(0.2);	
	turnLEDOff(red1);
	turnLEDOff(blue2);
	wait(0.2);
}
int darkness;


task main()
{
	while(true)
	{
		turnFlashlightOn(windowFlashlight1);
		turnFlashlightOn(windowFlashlight2);
		turnFlashlightOn(doorFlashlight);
		if(SensorValue(armSwitch) == 1)	//if you touch the arm button
		{
			wait(10);	//wait 10
			SensorValue(inLightSensor) = darkness;
		}
		if(SensorValue(inLightSensor) > darkness) //if the light senosor senses a higher light level
		{
			wait(5); 	//wait 5
			if(SensorValue(allClearSwitch) == 1) //if touch the all clear button
			{
				stopAllTasks(); //end program
			}
			else //else
			{
				LEDShow(); //light up LEDs
				if (SensorValue(outLightSensor) < 100) //if keyLightSensor gets a low value (lazer)
				{
					stopAllTasks(); //then end program
				}
			}
		}	
	}
}
