#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    inLightSensor,  sensorReflection)
#pragma config(Sensor, in4,    outLightSensor, sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorNone)
#pragma config(Sensor, dgtl4,  armSwitch,      sensorTouch)
#pragma config(Sensor, dgtl5,  allClearSwitch, sensorTouch)
#pragma config(Sensor, dgtl6,  red1,           sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           windowFlashlight1, tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           doorFlashlight, tmotorNone, openLoop)
#pragma config(Motor,  port5,           windowFlashlight2, tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void LEDControl(); //declare function


void LEDShow()
{
	turnLEDOn(red1);
}
int darkness;


task main()
{
	turnLEDoff(red1);
	while(true)
	{
		turnFlashlightOn(windowFlashlight1);
		turnFlashlightOn(windowFlashlight2);
		turnFlashlightOn(doorFlashlight);
		untiltouch(armSwitch);	//if you touch the arm button

			wait(10);	//wait 10
			darkness = SensorValue(inLightSensor);

		while(1==1)
		{
			if(SensorValue(inLightSensor) < darkness) //if the light senosor senses a higher light level
			{
				wait(5); 	//wait 5
				if(SensorValue(allClearSwitch) == 1) //if touch the all clear button
				{
					stopAllTasks(); //end program
				}
				else //else
				{
					while(SensorValue(outLightSensor) > 100)
						{
						LEDShow(); //light up LEDs
						wait(1)
						}

					while(SensorValue(outLightSensor) < 50)
						{
							turnLEDOff(red1);
							stopAllTasks();
						}
					}
			}
		}
	}
}
